import Image from "next/image"
import "../globals.css"

export const metadata = {
  title: "Current Location",
  description: "Generated by create next app",
}

export default function LocationLayout({
  children,
  aqi,
  temperature,
  weather,
  wind,
}) {
  return (
    <div className="wrapper">
      {/* <!-- image background and overlay --> */}
      <div className="overlay"></div>
      <Image
      priority
        fill
        alt="background image"
        src="/assets/images/background.png"
        className="bg-img object-cover"
      />

      {/* <div className="bg-img object-cover bg-hero-bg bg-center bg-no-repeat bg-cover" /> */}
      {/* <div className="bg-img object-cover bg-hero-bg bg-center "  style={{backgroundImage: `url(${bgImage})`}} /> */}
      <main className="!z-50 w-full">
        <div className="container">
          <div className="grid grid-cols-12 gap-y-8 py-16 lg:gap-8 2xl:gap-20 2xl:py-20">
            {children}
            {weather}
             {aqi} 
             {temperature} 
             {wind}
          </div>
        </div>
      </main>
    </div>
  )
}
